# Generated by Django 5.1.1 on 2024-11-06 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_account', to='banking.account'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_balance',
            field=models.BooleanField(default=False),
        ),
    ]
