# Generated by Django 5.1.1 on 2024-11-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transferedAccount',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
