"""
Django settings for banking_system project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path  # Modul az útvonalak kezelésére
import os  # Modul az operációs rendszerrel való interakcióhoz

# BASE_DIR: A projekt gyökérkönyvtárának útvonala
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECRET_KEY: A projekt titkos kulcsa, amelyet soha nem szabad nyilvánosan megosztani
SECRET_KEY = 'django-insecure-adczv^=-n$&y(lrc5-$0!!xuxk_zxzj9oj%_%eg$y%cv^=_h4r'

# DEBUG: Ha True, részletes hibainformációkat jelenít meg (fejlesztési környezethez)
DEBUG = True

# ALLOWED_HOSTS: A szerver által elfogadott domain nevek listája
ALLOWED_HOSTS = []  # Üresen hagyva fejlesztési környezetben

# Application definition

# INSTALLED_APPS: Az alkalmazások listája, amelyeket a Django kezel
INSTALLED_APPS = [
    'django.contrib.admin',  # Adminisztrációs felület
    'django.contrib.auth',  # Felhasználói hitelesítés
    'django.contrib.contenttypes',  # Típusok és modellek kezelése
    'django.contrib.sessions',  # Munkamenetkezelés
    'django.contrib.messages',  # Üzenetkezelés
    'django.contrib.staticfiles',  # Statikus fájlok kezelése
    'banking',  # Az egyedi alkalmazás (banking)
]

# MIDDLEWARE: Az alkalmazás köztes rétegei, amelyek kéréseket és válaszokat kezelnek
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # Biztonsági beállítások
    'django.contrib.sessions.middleware.SessionMiddleware',  # Munkamenetek kezelése
    'django.middleware.common.CommonMiddleware',  # Általános HTTP funkciók
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF védelem
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Felhasználói hitelesítés kezelése
    'django.contrib.messages.middleware.MessageMiddleware',  # Üzenetek kezelése
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Clickjacking elleni védelem
]

# ROOT_URLCONF: Az URL-konfiguráció alapértelmezett fájlja
ROOT_URLCONF = 'banking_system.urls'

# TEMPLATES: A sablonkezelő beállításai
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # A Django sablonmotorja
        'DIRS': [BASE_DIR / 'templates'],  # Egyéni sablonkönyvtárak
        'APP_DIRS': True,  # Automatikus sablonkeresés az alkalmazásokban
        'OPTIONS': {
            'context_processors': [  # Kiegészítő adatok az összes sablon számára
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # Kérés adatai elérhetők lesznek a sablonban
                'django.contrib.auth.context_processors.auth',  # Felhasználói adatok elérhetők a sablonban
                'django.contrib.messages.context_processors.messages',  # Üzenetek elérhetők a sablonban
            ],
        },
    },
]

# WSGI_APPLICATION: A WSGI alkalmazás belépési pontja
WSGI_APPLICATION = 'banking_system.wsgi.application'

# Database
# DATABASES: Az adatbázis-konfiguráció
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Az SQLite adatbázis motor
        'NAME': BASE_DIR / 'db.sqlite3',  # Az adatbázis fájl helye
    }
}

# Password validation: Jelszóval kapcsolatos szabályok és validációk
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # Hasonlóság a felhasználói attribútumokkal
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # Minimális jelszóhossz
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  # Gyakori jelszavak elutasítása
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  # Csak számokból álló jelszavak elutasítása
    },
]

# Internationalization: Nyelvi és időzóna beállítások
LANGUAGE_CODE = 'en-us'  # Alapértelmezett nyelv

TIME_ZONE = 'UTC'  # Alapértelmezett időzóna

USE_I18N = True  # Nemzetköziesítés bekapcsolása

USE_L10N = True  # Helyi formátumok használata

USE_TZ = True  # Időzóna-támogatás bekapcsolása

# LOGIN_URL: Alapértelmezett bejelentkezési URL
LOGIN_URL = '/login/'

# Static files (CSS, JavaScript, Images)
# STATIC_URL: Statikus fájlok elérési útja
STATIC_URL = '/static/'

# Default primary key field type
# DEFAULT_AUTO_FIELD: Az alapértelmezett elsődleges kulcs mezőtípus
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# MEDIA_ROOT: A feltöltött fájlok tárolási helye
STATIC_ROOT = BASE_DIR / "staticfiles"

# MEDIA_URL: A feltöltött fájlok URL-je
MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    BASE_DIR / "static",  # A "static" mappa a projekt gyökérkönyvtárában
]